name: Build and Release PDF

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run application
      run: java -jar target/pdf-generator-*.jar

    - name: Release PDF files
      uses: softprops/action-gh-release@v2
      with:
        files: "*.pdf"
